kind: pipeline
name: axentix new release

steps:
- name: install
  image: node:14-alpine
  commands:
  - apk add python make g++
  - npm ci
  when:
    event:
      - tag

- name: build
  image: node:14-alpine
  commands:
  - npm run build
  when:
    event:
      - tag

- name: make zip folder
  image: node:14-alpine
  commands:
  - apk add zip
  - cp -R ./dist ./axentix-v${DRONE_TAG}
  - cp CHANGELOG.md ./axentix-v${DRONE_TAG}/CHANGELOG.md
  - cp LICENSE ./axentix-v${DRONE_TAG}/LICENSE
  - cp README.md ./axentix-v${DRONE_TAG}/README.md
  - zip -r ./axentix-v${DRONE_TAG}.zip ./axentix-v${DRONE_TAG}
  when:
    event:
      - tag

- name: github release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_auth
    files:
      - axentix-v${DRONE_TAG}.zip
  when:
    event:
      - tag

- name: publish to npm
  image: plugins/npm
  settings:
    token:
      from_secret: npm_token
    email:
      from_secret: publish_email
  when:
    event:
      - tag

- name: send
  image: plugins/webhook
  settings:
    urls: https://useaxentix.com/api/hook
    headers:
      from_secret: hook_headers
    template: |
      {
        "version": "{{ build.tag }}"
      }
  when:
    event:
      - tag