---
name: tests

on:
  push:
    branches:
      - '**'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: microsoft/playwright-github-action@v1
    
    - name: Install deps, build & run tests
      run: npm ci
      run: npm run build
      run: npm run test
