---
name: tests

on:
  push:
    branches:
      - '**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
      - run: npm ci
      - run: npm run build
      - run: npm run test